# syntax=docker/dockerfile:1.7-labs
FROM node:22-alpine

LABEL org.opencontainers.image.source=https://github.com/Krzysztoff27/catmonit
LABEL org.opencontainers.image.description="Catmonit Dashboard"
LABEL org.opencontainers.image.licenses=MIT

WORKDIR /app

COPY ./package.json /app/package.json

RUN npm install
RUN npm i -g serve

COPY --exclude=./package.json --exclude=./docker ./ /app

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-l", "3000", "-s", "dist" ]