
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: catmonit
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks: 
      - backend
    
  aspnetapp:
    build:
        context: .
        dockerfile: ./webapi/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=catmonit;User=root;Password=mysecretpassword;

networks:
    backend:
        driver: bridge
        driver_opts: 
            com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"

volumes:
  mysql-data:
  