services:
  grpc.telemetry.server:
    image: grpc.telemetry.server
    build:
      context: .
      dockerfile: gRPC.telemetry.Server/Dockerfile
    networks:
        - catmonit-network

networks:
  catmonit-network:
    name: catmonit-network
    external: true