services:
  database:
    container_name: catmonit-db
    restart: always
    image: postgres
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dbvolume:/var/lib/postgresql/data
      - /opt/catmonit-telemetry-server/telemetry-server/telemetry-server/Database/db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/:ro
    networks:
        - catmonit-network

networks:
  catmonit-network:
    name: catmonit-network
    external: false
    
volumes:
    dbvolume: {}
