# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\ttelemetry\"\xf3\x01\n\x10TelemetryRequest\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x18\n\x10operating_system\x18\x04 \x01(\t\x12.\n\x07network\x18\x05 \x01(\x0b\x32\x1b.telemetry.NetworkStatsListH\x00\x12)\n\x05\x64isks\x18\x06 \x01(\x0b\x32\x18.telemetry.DiskStatsListH\x00\x12+\n\x06shares\x18\x07 \x01(\x0b\x32\x19.telemetry.FileSharesListH\x00\x42\t\n\x07payload\"<\n\x10NetworkStatsList\x12(\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x17.telemetry.NetworkStats\"m\n\x0cNetworkStats\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\x12\x0f\n\x07rx_mbps\x18\x02 \x01(\x01\x12\x0f\n\x07tx_mbps\x18\x03 \x01(\x01\x12\x11\n\x07is_main\x18\x04 \x01(\x08H\x00\x42\x10\n\x0einterface_role\"6\n\rDiskStatsList\x12%\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x14.telemetry.DiskStats\"A\n\tDiskStats\x12\x13\n\x0bmount_point\x18\x01 \x01(\t\x12\r\n\x05usage\x18\x02 \x01(\x03\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x03\"8\n\x0e\x46ileSharesList\x12&\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x15.telemetry.FileShares\"A\n\nFileShares\x12\x12\n\nshare_path\x18\x01 \x01(\t\x12\r\n\x05usage\x18\x02 \x01(\x03\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x03\"#\n\x11TelemetryResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2b\n\x10TelemetryService\x12N\n\x0fStreamTelemetry\x12\x1b.telemetry.TelemetryRequest\x1a\x1c.telemetry.TelemetryResponse(\x01\x42\x11\xaa\x02\x0egRPC.telemetryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\016gRPC.telemetry'
  _globals['_TELEMETRYREQUEST']._serialized_start=31
  _globals['_TELEMETRYREQUEST']._serialized_end=274
  _globals['_NETWORKSTATSLIST']._serialized_start=276
  _globals['_NETWORKSTATSLIST']._serialized_end=336
  _globals['_NETWORKSTATS']._serialized_start=338
  _globals['_NETWORKSTATS']._serialized_end=447
  _globals['_DISKSTATSLIST']._serialized_start=449
  _globals['_DISKSTATSLIST']._serialized_end=503
  _globals['_DISKSTATS']._serialized_start=505
  _globals['_DISKSTATS']._serialized_end=570
  _globals['_FILESHARESLIST']._serialized_start=572
  _globals['_FILESHARESLIST']._serialized_end=628
  _globals['_FILESHARES']._serialized_start=630
  _globals['_FILESHARES']._serialized_end=695
  _globals['_TELEMETRYRESPONSE']._serialized_start=697
  _globals['_TELEMETRYRESPONSE']._serialized_end=732
  _globals['_TELEMETRYSERVICE']._serialized_start=734
  _globals['_TELEMETRYSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
