services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: dnsmasq
    restart: unless-stopped
    command:
      - "--log-facility=-"
      - "--address=/api-machines.local/10.10.51.3"
      - "--address=/api-web.local/10.10.51.3"
      - "--listen-address=0.0.0.0"
      - "--no-daemon"
      - "--log-queries"
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    cap_add:
      - NET_ADMIN