version: "3.8"

services:
  dnsmasq:
    image: jpillora/dnsmasq
    container_name: catmonit-dns
    restart: unless-stopped
    command:
      - "--log-facility=-"
      - "--address=/dashboard.local/10.10.51.3"
      - "--address=/api-machines.local/10.10.51.3"
      - "--address=/api-web.local/10.10.51.3"
      - "--address=/traefik.local/10.10.51.3"
      - "--listen-address=0.0.0.0"
      - "--no-resolv"
      - "--no-hosts"
      - "--no-daemon"
      - "--log-queries"
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    cap_add:
      - NET_ADMIN
