version: "3.8"

services:
  dnsmasq:
    image: dockurr/dnsmasq
    container_name: catmonit-dns
    restart: unless-stopped
    environment:
      DNS1: "api-web.local=10.10.51.3"
      DNS2: "api-machines.local=10.10.51.3"
    ports:
      - "5353:53/udp"
      - "5353:53/tcp"
    cap_add:
      - NET_ADMIN
