log:
  level: DEBUG

entryPoints:
  websecure:
    address: ":443"

  grpsecure:
    address: ":444"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true