services:
  traefik:
    container_name: catmonit-proxy
    restart: always
    image: traefik:v3.0
    command:
    - "--log.level=DEBUG"

    # Static configuration
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--entrypoints.grpcsecure.address=:444"

    - "--providers.docker=true"
    - "--providers.docker.exposedByDefault=false"
    - "--providers.file.directory=/etc/traefik/dynamic"  # Optional — remove if unused
    - "--providers.file.watch=true"

     #Let's Encrypt certificate resolver
    - "--certificatesresolvers.le.acme.tlschallenge=true"
    - "--certificatesresolvers.le.acme.email=root@example.com"
    - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

    - "--api.dashboard=true" # Optional - comment to turn the dashboard off
    ports:
      - "443:443" # telemetry-server websockets/requests entrypoint + dashboard entrypoint
      - "444:444" # telemetry-server machines entrypoint
      - "80:80"
      - "8080:8080"  # Optional: Traefik dashboard
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./traefik/dynamic.yaml:/etc/traefik/dynamic/dynamic.yaml:ro"
    - "./traefik/certs:/etc/traefik/certs:ro"
    - "./traefik/letsencrypt:/letsencrypt"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
    - "traefik.http.routers.traefik.entrypoints=websecure"
    - "traefik.http.routers.traefik.service=api@internal"
    - "traefik.http.routers.traefik.tls.certresolver=le"
    networks:
      - catmonit-network

  database:
    container_name: catmonit-db
    restart: always
    image: postgres
    env_file:
      - ./.env 
    volumes:
      - ./database/db:/var/lib/postgresql/data
      - ./database/initdb:/docker-entrypoint-initdb.d/:ro
    networks:
        - catmonit-network

  grpc.telemetry.server:
    container_name: catmonit-telemetry-server
    restart: always
    image: "ghcr.io/krzysztoff27/catmonit-telemetry-server:latest"
    env_file:
      - ./.env
    labels:
    - "traefik.enable=true"

    #gRPC router
    - "traefik.http.routers.api-machines.rule=Host(`api-machines.local`)"
    - "traefik.http.routers.api-machines.entrypoints=grpcsecure"
    - "traefik.http.routers.api-machines.tls=true"
    - "traefik.http.routers.api-machines.service=api-machines"
    - "traefik.http.services.api-machines.loadbalancer.server.port=5001"

    #HTTP router
    - "traefik.http.routers.api-web.rule=Host(`api-web.local`)"
    - "traefik.http.routers.api-web.entrypoints=websecure"
    - "traefik.http.routers.api-web.tls.certresolver=le"
    - "traefik.http.routers.api-web.service=api-web"
    - "traefik.http.services.api-web.loadbalancer.server.port=5172"
    networks:
      - catmonit-network

  website:
      container_name: catmonit-dashboard
      restart: always
      image: "ghcr.io/krzysztoff27/catmonit-dashboard:latest"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.website.rule=Host(`dashboard.local`)"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.tls.certresolver=le"
        - "traefik.http.routers.website.service=website"
        - "traefik.http.services.website.loadbalancer.server.port=3000"
      networks:
        - catmonit-network

networks:
  catmonit-network:
    name: catmonit-network
    external: false