services:
  traefik:
    container_name: catmonit-proxy
    restart: always
    image: traefik:v3.0
    command:
    - "--providers.docker=true"
    - "--providers.file.directory=/etc/traefik/dynamic"
    - "--entrypoints.websecure.address=:443"
    - "--entrypoints.web.address=:80"
    - "--certificatesresolvers.le.acme.tlschallenge=true"
    - "--certificatesresolvers.le.acme.email=root@example.com"
    - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    - "--api.dashboard=true" # Optional - comment to turn the dashboard off
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"  # Optional: Traefik dashboard
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    - "./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro"
    - "./traefik/certs:/etc/traefik/certs:ro"
    - "./traefik/letsencrypt:/letsencrypt"
    networks:
      - catmonit-network

  database:
    container_name: catmonit-db
    restart: always
    image: postgres
    env_file:
      - ./.env 
    volumes:
      - ./database/db:/var/lib/postgresql/data
      - ./database/initdb:/docker-entrypoint-initdb.d/:ro
    networks:
        - catmonit-network

  grpc.telemetry.server:
    container_name: catmonit-telemetry-server
    restart: always
    image: "ghcr.io/krzysztoff27/catmonit-telemetry-server:latest"
    env_file:
      - ./.env
    labels:
    - "traefik.enable=true"

    - "traefik.http.routers.api-machines.rule=Host(`api-machines.local`)"
    - "traefik.http.routers.api-machines.entrypoints=websecure"
    - "traefik.http.routers.api-machines.tls=true"
    - "traefik.http.services.api-machines.loadbalancer.server.port=5001"

    - "traefik.http.routers.api-mobile.rule=Host(`api-mobile.local`)"
    - "traefik.http.routers.api-mobile.entrypoints=websecure"
    - "traefik.http.routers.api-mobile.tls.certresolver=le"
    - "traefik.http.services.api-mobile.loadbalancer.server.port=5172"
    networks:
      - catmonit-network
    #volumes:
      #- "/opt/catmonit/backend/backend/Docker/telemetry-server/certs/server.pfx:/app/SSL/server.pfx:ro"

  website:
      container_name: catmonit-dashboard
      restart: always
      image: "ghcr.io/krzysztoff27/catmonit-dashboard:latest"
      profiles: ["dashboard"]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.website.rule=Host(`dashboard.local`)"
        - "traefik.http.routers.website.entrypoints=websecure"
        - "traefik.http.routers.website.tls.certresolver=le"
        - "traefik.http.services.website.loadbalancer.server.port=3000"
      networks:
        - catmonit-network

networks:
  catmonit-network:
    name: catmonit-network
    external: false