name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    if: github.event.release.target_commitish == 'telemetry-client'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r telemetry-client/src/windows/requirements.txt
          pip install pyinstaller

      - name: Build executable
        working-directory: telemetry-client/src/windows
        run: pyinstaller service.spec

      - name: Prepare ZIP archive for release
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          mkdir release
          cp telemetry-client/src/windows/dist/CatMonitTelemetryClient.exe release/
          cp telemetry-client/src/windows/installer/*.ps1 release/
          cd release
          zip "../catmonit-${TAG_NAME}.zip" *

      - name: Upload ZIP archive to the same GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          name: "CatMonit Telemetry Client ${{ github.event.release.tag_name }}"
          generate_release_notes: true
          prerelease: true
          make_latest: true
          files: catmonit-${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
