name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all refs/tags are available

      - name: Ensure tag is from telemetry-client branch
        run: |
          BRANCH=$(git branch --contains ${{ github.ref }})
          echo "Branch: $BRANCH"
          if [[ "$BRANCH" != *"telemetry-client"* ]]; then
            echo "This tag is not on the telemetry-client branch."
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r telemetry-client/src/requirements.txt
          pip install pyinstaller

      - name: Build executable
        working-directory: telemetry-client/src
        run: pyinstaller service.spec

      - name: Prepare release folder and zip with tag name
        run: |
          TAG_NAME=${{ github.ref_name }}
          mkdir release
          cp telemetry-client/src/dist/CatMonitTelemetryClient.exe release/
          cp telemetry-client/src/installer/*.ps1 release/
          cd release
          zip "../catmonit-${TAG_NAME}.zip" *

      - name: Upload ZIP archive to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "CatMonit Telemetry Client ${{ github.ref_name }}"
          generate_release_notes: true
          prerelease: true
          make_latest: true
          files: catmonit-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
