name: Build and Release (Windows)

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure tags and history are available

      - name: Verify release commit is on telemetry-client branch
        run: |
          $releaseSha = "${{ github.event.release.target_commitish }}"
          git fetch origin telemetry-client
          $mergeBase = git merge-base origin/telemetry-client $releaseSha
          if ($mergeBase -ne $releaseSha) {
            Write-Host "Release commit is not on telemetry-client branch. Exiting."
            exit 1
          }

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r telemetry-client/src/windows/requirements.txt
          pip install pyinstaller

      - name: Build executable
        working-directory: telemetry-client/src
        run: pyinstaller service.spec

      - name: Prepare ZIP artifact
        run: |
          $tag = "${{ github.ref_name }}"
          $zipName = "catmonit-$tag.zip"
          New-Item -ItemType Directory -Path release
          Copy-Item telemetry-client/src/dist/CatMonitTelemetryClient.exe -Destination release/
          Copy-Item telemetry-client/src/installer/*.ps1 -Destination release/
          Compress-Archive -Path release/* -DestinationPath $zipName

      - name: Upload ZIP to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "CatMonit Telemetry Client ${{ github.ref_name }}"
          generate_release_notes: true
          prerelease: true
          make_latest: true
          files: catmonit-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
